feature_engineering:
  vectorizer:
    type: "TfidfVectorizer"
    params:
      analyzer: "word"
      ngram_range: "1, 3"
      min_df: 10
      max_df: 0.7
      sublinear_tf: true
      max_features: 20000
      # stop_words: dışarıdan inject edilecek (azerbaijani_stopwords listesi)

training:
  model:
    type: "MultinomialNB"
    params: {}  # MultinomialNB varsayılan hiperparametreler

  split:
    test_size: 0.2
    random_state: 42
    stratify: true

  evaluation:
    cv_folds: 5
